### ISSUE TITLE
Installation Error V2.54

### ISSUE THREAD

**Issue by abgunes** [arteeecz/KPSAPLunch#3]
Hi  @arteeecz ,

I am getting following error, i used the latest release [KPSAPLunch.plgx](https://github.com/arteeecz/KeePass-plugins/releases/download/v1.1.0.5/KPSAPLunch.plgx).

![image](https://github.com/arteeecz/KeePass-plugins/assets/12530594/1722d9d0-0c0f-41b0-b5e2-3492f77e9c74)

**Comment by arteeecz** [comment]
Hi @abgunes ,
please try the new version of plugin that I just released. 
When I tried the plugin with version 2.54 the error wasn't occurred to me, so I tried to make changes related to exception from your screen.

New release:
[v1.0.0.6](https://github.com/arteeecz/KeePass-plugins/releases/tag/v1.1.0.6)

**Comment by abgunes** [comment]
Hi @arteeecz ,

Thanks for the new version but I get the same error.
I downloaded the **.plgx** file of the new version and copied it to "**C:\Program Files (x86)\KeePass2x\Plugins**" folder and then tried it.

P.S: I can use KeePassV2.54 with other plugins.


![image](https://github.com/arteeecz/KeePass-plugins/assets/12530594/8f2321b8-5735-4b35-9452-b9214958e566)

**Comment by arteeecz** [comment]
Hi @abgunes ,
I believe I have fixed source of your problem. Please try new release [v1.1.0.7](https://github.com/arteeecz/KeePass-plugins/releases/tag/v1.1.0.7).

**Comment by ramonroquefilho** [comment]
Hi @arteeecz .
First, I would like to congratulate you on your work.
I updated to the latest version v1.1.0.7 and carried out the procedure of moving the file to the proper folder.
The following error was returned when opening KeePass2
![image](https://github.com/arteeecz/KeePass-plugins/assets/139164501/e37dbe68-2fb7-4cfb-a5a6-dc8bd1780c40)

**Comment by arteeecz** [comment]
Hi guys (@abgunes, @ramonroquefilho),
I'm so sorry. I had trouble simulate your issue, so all fixies until this moment were blind attempts :) I not realized mixing KP config files when I use "installed" version of KP and testing with "portable" version makes me an obstacle to simulate your error.

I hope, this version is the true one :)
[latest](https://github.com/arteeecz/KeePass-plugins/releases/latest)

**Comment by abgunes** [comment]
Hi @arteeecz ,

Thanks for the solution, it works now with the latest version.
